Ami readmi
dbeaver/team-edition-deploy pull request #11
Opened 2023-09-01 09:08 UTC by ggxed

2023-09-01 09:16 UTC, serge-rider requested changes

2023-09-01 09:16 UTC, serge-rider commented on ami/README.md
> +* 8Gb RAM
16gb

2023-09-01 09:16 UTC, serge-rider commented on ami/README.md
> +
Please add information how to deploy AMI

2023-09-04 10:13 UTC, serge-rider commented on ami/README.md
> +
And also info about storage, 100gb minimum

2023-09-07 07:47 UTC, arhayka reviewed
Some micro changes :)

2023-09-07 07:47 UTC, arhayka commented on ami/README.md
> +* 16Gb RAM
* 16GB RAM

2023-09-07 07:47 UTC, arhayka commented on ami/README.md
> +* 100G Storage (SSD recommended)
* 100GB Storage (SSD recommended)

2023-09-07 07:47 UTC, arhayka commented on ami/README.md
> +- For your secure not recommended make the service public
- For security reasons, it is not recommended to make the service public

2023-09-07 07:47 UTC, arhayka commented on ami/README.md
> +- Choose the version which you want to update
- Choose the version you want to update

2023-09-07 07:47 UTC, arhayka commented on README.md
> +- [AWS AMI](ami) - if you want use AWS for deploy
- [AWS AMI](ami) - if you want to use AWS for deployment

2023-09-12 13:06 UTC, closed without merging